### ISSUE TITLE
File dissapearing when processing multiple timesteps in a row

### ISSUE THREAD

**Issue by omaralvarez** [fluiddyn/fluidfoam#55]
I have a weird problem and not sure why. I have the following code:

``` python
for j, t in enumerate(timesteps):
                # Read data
                vel = readvector(path, t, "U", verbose=args.verbose)
                p = readscalar(path, t, "p", verbose=args.verbose)
```

In some timesteps when I read `p` it fails and dissapears from the filesystem:

```bash
Traceback (most recent call last):
  File "mlwind\source\getbounds.py", line 80, in <module>
    main(parser.parse_args())
  File "mlwind\source\getbounds.py", line 54, in main
    p = readscalar(path, t, "p", verbose=args.verbose)
  File "fluidfoam\readof.py", line 750, in readscalar
    scalar = OpenFoamFile(
  File "fluidfoam\readof.py", line 100, in __init__
    with self._open(self.path, "rb") as f:
OSError: [Errno 22] Invalid argument: '..\\..\\mlwind2\\1.007875\\p'
```

I'm on Windows 11 x64, Python 3.10.13, fluidfoam 0.2.5.

Any ideas on what can be happening here? I'm totally puzzled.

**Comment by omaralvarez** [comment]
Thanks for the quick answer, I think I found the culprit. Windows is interpreting the p file as a trojan, and Windows Defender is removing it. Not sure what is going on. I do not think it is the library's fault.
